# Generated by Django 4.1.7 on 2023-07-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0003_alter_orderitem_customization_details_order_and_more'),
        ('app_staff_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
