# Generated by Django 4.1.7 on 2023-07-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_staff_dashboard', '0001_initial'),
        ('app_owner_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('customization_details', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner_admin_panel.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_staff_dashboard.order')),
            ],
        ),
    ]
