# Generated by Django 4.1.7 on 2023-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('restaurant_id', models.IntegerField()),
            ],
        ),
    ]
