# Generated by Django 4.1.7 on 2023-07-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0003_remove_restaurant_user_clientprofile'),
        ('app_customer_interface', '0002_qrcodescanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customization_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('status', models.CharField(default='Placed', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('order_number_of_the_day', models.PositiveIntegerField(default=1)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner_admin_panel.restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_customer_interface.order'),
        ),
    ]
