# Generated by Django 4.1.7 on 2023-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0003_alter_orderitem_customization_details_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
