# Generated by Django 4.1.7 on 2023-08-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0004_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number_of_the_day',
        ),
    ]
