# Generated by Django 4.1.7 on 2023-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0005_remove_order_order_number_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
