# Generated by Django 4.1.7 on 2023-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0006_orderitem_extra_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
