# Generated by Django 4.1.7 on 2023-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
