# Generated by Django 4.2.9 on 2024-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('已送出', '已送出'), ('製作中', '製作中'), ('已確認', '已確認'), ('完成', '完成'), ('已取消', '已取消')], default='已送出', max_length=50),
        ),
    ]
