# Generated by Django 4.2.9 on 2024-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processing', 'processing'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('canceled', 'canceled')], default='placed', max_length=50),
        ),
    ]
