# Generated by Django 4.2.9 on 2024-09-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0015_alter_order_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCodeScanner',
        ),
    ]
