# Generated by Django 4.2.9 on 2025-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0017_alter_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processing', 'processing'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('canceled', 'canceled')], default='placed', max_length=50),
        ),
    ]
