# Generated by Django 4.2.9 on 2025-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0018_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processing', 'processing'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('canceled', 'canceled')], default='placed', max_length=50),
        ),
    ]
