# Generated by Django 4.2.20 on 2025-06-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0019_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('eat_in', 'Eat In'), ('take_out', 'Take Out'), ('delivery', 'Delivery')], default='eat_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
