# Generated by Django 4.2.20 on 2025-06-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_interface', '0020_order_delivery_address_order_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
