# Generated by Django 4.1.7 on 2023-08-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0003_remove_restaurant_user_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_selection', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner_admin_panel.customizationcategory')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='customization_categories',
            field=models.ManyToManyField(blank=True, to='app_owner_admin_panel.customizationcategory'),
        ),
    ]
