# Generated by Django 4.1.7 on 2023-08-27 09:56

from django.db import migrations, models

def create_initial_system_configuration(apps, schema_editor):
    SystemConfiguration = apps.get_model('app_owner_admin_panel', 'SystemConfiguration')
    if not SystemConfiguration.objects.exists():
        SystemConfiguration.objects.create(
            system_open=False,
            opening_time="10:00:00",
            closing_time="20:00:00",
            automatic_management=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0005_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='closing_time',
            field=models.TimeField(default='20:00:00'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='opening_time',
            field=models.TimeField(default='10:00:00'),
        ),

        migrations.RunPython(create_initial_system_configuration),
    ]