# Generated by Django 4.1.7 on 2023-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0006_systemconfiguration_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='customization_options',
            field=models.ManyToManyField(blank=True, to='app_owner_admin_panel.customizationoption'),
        ),
    ]
