# Generated by Django 4.1.7 on 2023-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0007_dish_customization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_table_number',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_table_number',
            field=models.IntegerField(default=1),
        ),
    ]
