# Generated by Django 4.1.7 on 2023-09-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0008_restaurant_max_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='system_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
