# Generated by Django 4.1.7 on 2023-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0009_alter_systemconfiguration_system_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='automatic_management',
            field=models.BooleanField(default=True),
        ),
    ]
