# Generated by Django 4.1.7 on 2023-09-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0010_systemconfiguration_automatic_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
