# Generated by Django 4.2.9 on 2024-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0011_dish_is_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='logo',
        ),
    ]
