# Generated by Django 4.2.9 on 2024-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0012_remove_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
