# Generated by Django 4.2.9 on 2024-09-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0013_dish_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
