# Generated by Django 4.2.9 on 2025-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0014_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dish_time_warning',
            field=models.IntegerField(default=30, help_text='Time in minutes after which the order timestamp turns red'),
        ),
    ]
