# Generated by Django 4.2.9 on 2025-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0016_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AddField(
            model_name='dish',
            name='image_16x9',
            field=models.ImageField(blank=True, help_text='16x9 ratio image', null=True, upload_to='dish_images/16x9/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_1x1',
            field=models.ImageField(blank=True, help_text='1x1 ratio image', null=True, upload_to='dish_images/1x1/'),
        ),
    ]
