# Generated by Django 4.2.20 on 2025-06-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner_admin_panel', '0017_remove_dish_image_dish_image_16x9_dish_image_1x1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image_name',
        ),
    ]
